### ISSUE TITLE
list all use cases you remember - in fact test cases

### ISSUE THREAD

**Issue by statistics101** [statistics101/product2#35]

**Comment by av1611** [comment]
Creating all data structures that have been created in this iteration:
cMatrix vs cHatMatrix
dMatrix vs dHatMatrix
a snake-like column-wise plot for triangle productCol matrix
a snake-like column-wise plot for betaArray
export to JPEG
export to CSV(?)

**Comment by statistics101** [comment]
Write in details in OneNote R product / use cases

**Comment by statistics101** [comment]
Moved to R product test
separate pages for each test

**Comment by statistics101** [comment]
A listed
