### ISSUE TITLE
bug in ExportOriginal

### ISSUE THREAD

**Issue by Gograman** [statistics101/product2#37]
Testing 'tests_73_ExportOriginal' 
Test parameters: 
size = 10 
sigma = 1 
psi = 0.5 
mean = 0 
replicationCount = 10 
Error: Test failed: 'Testing exportOriginal'
* argument "psi" is missing, with no default
1: testUtilExportOriginal(replicationCount = 10, size = 10, psi = 0.5, 
       sigma = 1, mean = 0) at :3
2: exportOriginal(original1d) at C:\product2n\product2/R/testUtilExportOriginal.R:15
3: paste0("original_size_", size, "_psi_", psi, "_sigma_", sigma, ".csv") at

**Comment by Kosmos42** [comment]
done
