### ISSUE TITLE
think: productCol is data frame while beta and other are matrices

### ISSUE THREAD

**Issue by statistics101** [statistics101/product2#52]
productCol <- as.data.frame(productCol)
  colnames(productCol) <- as.character(0:(lengthOriginal - 1))

  productCol
}

**Comment by statistics101** [comment]
================

Failed -------------------------------------------------------------------------
1. Error: Testing all 'product2' environment,

                  using both testthat tests and manual tests (@tests_00_testEverything.R#54) 
'ts' object must have one or more observations
1: testUtilCreateCHatMatrix(size = size, psi = psi, sigma = sigma, mean = mean) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/tests/testthat/tests_00_testEverything.R:54
2: createCHatMatrix(productCol) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/testUtilCreateCHatMatrix.R:15
3: acf(ithProdColWithoutNA, type = "covariance") at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/createCHatMatrix.R:33
4: na.action(as.ts(x))
5: as.ts(x)
6: as.ts.default(x)
7: ts(x)
8: stop("'ts' object must have one or more observations")

2. Error: Testing createCHatMatrix for dimensions (@tests_31_createCHatMatrix.R#6) 
'ts' object must have one or more observations
1: testUtilCreateCHatMatrix(size = 10, psi = 0.5, sigma = 1, mean = 0) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/tests/testthat/tests_31_createCHatMatrix.R:6
2: createCHatMatrix(productCol) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/testUtilCreateCHatMatrix.R:15
3: acf(ithProdColWithoutNA, type = "covariance") at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/createCHatMatrix.R:33
4: na.action(as.ts(x))
5: as.ts(x)
6: as.ts.default(x)
7: ts(x)
8: stop("'ts' object must have one or more observations")

3. Error: Testing createDiffCMatrixVsCHatMatrix (@tests_51_createDiffCMatrixVsCHatMatrix.R#3) 
'ts' object must have one or more observations
1: testUtilCreateDiffCMatrixVsCHatMatrix(size = 10, psi = 0.5, sigma = 1, mean = 0) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/tests/testthat/tests_51_createDiffCMatrixVsCHatMatrix.R:3
2: createCHatMatrix(productCol = productCol) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/testUtilCreateDiffCMatrixVsCHatMatrix.R:26
3: acf(ithProdColWithoutNA, type = "covariance") at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/createCHatMatrix.R:33
4: na.action(as.ts(x))
5: as.ts(x)
6: as.ts.default(x)
7: ts(x)
8: stop("'ts' object must have one or more observations")

4. Error: Testing drawCVsCHat (@tests_61_drawCVsCHat.R#3) ----------------------
'ts' object must have one or more observations
1: testUtilDrawCVsCHat(size = 10, psi = 0.5, sigma = 1, mean = 0) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/tests/testthat/tests_61_drawCVsCHat.R:3
2: createCHatMatrix(productCol = productCol) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/testUtilDrawCvsCHat.R:25
3: acf(ithProdColWithoutNA, type = "covariance") at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/createCHatMatrix.R:33
4: na.action(as.ts(x))
5: as.ts(x)
6: as.ts.default(x)
7: ts(x)
8: stop("'ts' object must have one or more observations")

5. Error: Testing BenchmarkCreateCHatMatrix (@tests_89_BenchmarkCreateCHatMatrix.R#3) 
'ts' object must have one or more observations
1: testUtilBenchmarkCreateCHatMatrix(sizeArray = seq(10, 20, 5), psi = 0.5, sigma = 1, 
       mean = 0) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/tests/testthat/tests_89_BenchmarkCreateCHatMatrix.R:3
2: microbenchmark(createCHatMatrix(productCol = productCol), times = 10L) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/testUtilBenchmarkCreateCHatMatrix.R:29
3: createCHatMatrix(productCol = productCol)
4: acf(ithProdColWithoutNA, type = "covariance") at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/createCHatMatrix.R:33
5: na.action(as.ts(x))
6: as.ts(x)
7: as.ts.default(x)
8: ts(x)
9: stop("'ts' object must have one or more observations")

DONE ===========================================================================
Files
Plots
Packages
Help
Viewer

	
New Folder
	
	
Delete

	
Rename
	
	
More


			
Go to project directoryGo to directory
C:	Users	Boris	OneDrive	text	toronto_u	research	zhou	r	product2	product2	R



Name
Size	Modified

..


computeBetaLRVArrayPsi0.R
691 B
Nov 6, 2017, 9:15 AM


computeBetaLRVpsi0.R
446 B
Nov 6, 2017, 9:15 AM


createBetaArray.R
1.9 KB
Nov 6, 2017, 9:15 AM


createBetaArrayReplicated.R
1.4 KB
Nov 6, 2017, 9:15 AM


createCHatMatrix.R
1.7 KB
Nov 6, 2017, 9:15 AM


createCHatMatrixInALoop.R
1.2 KB
Nov 6, 2017, 9:15 AM


createCMatrix.R
1.3 KB
Nov 13, 2017, 9:20 AM


createDHatMatrix.R
1.9 KB
Nov 17, 2017, 9:35 AM


createDiffCMatrixVsCHatMatrix.R
2 KB
Nov 6, 2017, 9:15 AM


createDiffDMatrixVsDHatMatrix.R
1.9 KB
Nov 6, 2017, 9:15 AM


createDMatrix.R
1.3 KB
Nov 6, 2017, 9:15 AM


createGamma.R
570 B
Nov 6, 2017, 9:15 AM


createLRVof2dArray.R
1.5 KB
Nov 10, 2017, 9:56 AM


createLRVof3dArray.R
1.2 KB
Nov 6, 2017, 9:15 AM


createNonCenteredLRVof2dArray.R
1.5 KB
Nov 9, 2017, 3:20 PM


createOriginalMA1.R
1.1 KB
Nov 17, 2017, 9:35 AM


createOriginalMA1Replicated.R
1.7 KB
Nov 17, 2017, 9:35 AM


createProductCol.R
1.4 KB
Nov 27, 2017, 9:30 AM


createProductColReplicated.R
1.1 KB
Nov 17, 2017, 9:35 AM


createRho.R
566 B
Nov 6, 2017, 9:15 AM


cutNB.R
548 B
Nov 27, 2017, 9:11 AM


cutOB.R
335 B
Nov 27, 2017, 9:11 AM


drawCvsCHat.R
1.5 KB
Nov 6, 2017, 9:15 AM


drawDvsDHat.R
1.6 KB
Nov 6, 2017, 9:15 AM


drawLrvHatVsTSAVsBasePeriodogram.R
2.8 KB
Nov 15, 2017, 9:08 AM


drawOriginalLrvHat.R
1.5 KB
Nov 10, 2017, 8:59 AM


drawProductCol.R
2.2 KB
Nov 6, 2017, 9:15 AM


drawVectorLrvVsLrvHat.R
2.6 KB
Nov 15, 2017, 9:08 AM


drawVectorLrvVsLrvHatForSize.R
3.2 KB
Nov 10, 2017, 8:59 AM


exportOriginal.R
1.2 KB
Nov 6, 2017, 9:15 AM


getReplicationCountFromSampleSize.R
87 B
Nov 6, 2017, 9:15 AM


lrvProductColReplicated.R
365 B
Nov 6, 2017, 9:15 AM


saveJpg.R
760 B
Nov 6, 2017, 9:15 AM


saveProductCol.R
748 B
Nov 6, 2017, 9:15 AM


testUtilBenchmarkCreateBetaArray.R
2.6 KB
Nov 24, 2017, 9:14 AM


testUtilBenchmarkCreateBetaArrayReplicated.R
2.9 KB
Nov 24, 2017, 9:14 AM


testUtilBenchmarkCreateCHatMatrix.R
2.8 KB
Nov 24, 2017, 9:14 AM


testUtilBenchmarkCreateCMatrix.R
2.6 KB
Nov 22, 2017, 9:29 AM


testUtilBenchmarkCreateDHatMatrix.R
2.9 KB
Nov 24, 2017, 9:14 AM


testUtilBenchmarkCreateDMatrix.R
2.6 KB
Nov 22, 2017, 9:29 AM


testUtilBenchmarkCreateOriginalMA1.R
2.5 KB
Nov 22, 2017, 9:29 AM


testUtilBenchmarkCreateOriginalMA1Replicated.R
3 KB
Nov 22, 2017, 9:29 AM


testUtilBenchmarkCreateProductCol.R
2.7 KB
Nov 22, 2017, 9:29 AM


testUtilBenchmarkCreateProductColReplicated.R
2.9 KB
Nov 24, 2017, 9:14 AM


testUtilComputeBetaLRVArrayPsi0.R
570 B
Nov 6, 2017, 9:15 AM


testUtilCreateBetaArray.R
1.2 KB
Nov 6, 2017, 9:15 AM


testUtilCreateBetaArrayReplicated.R
1.7 KB
Nov 6, 2017, 9:15 AM


testUtilCreateCHatMatrix.R
1.2 KB
Nov 6, 2017, 9:15 AM


testUtilCreateCMatrix.R
900 B
Nov 6, 2017, 9:15 AM


testUtilCreateDHatMatrix.R
1.3 KB
Nov 18, 2017, 9:05 AM


testUtilCreateDiffCMatrixVsCHatMatrix.R
1.3 KB
Nov 6, 2017, 9:15 AM


testUtilCreateDiffDMatrixVsDHatMatrix.R
1.4 KB
Nov 19, 2017, 9:18 AM


testUtilCreateDMatrix.R
916 B
Nov 6, 2017, 9:15 AM


testUtilCreateGamma.R
710 B
Nov 6, 2017, 9:15 AM


testUtilCreateLRVof2dArrayForOriginalRC.R
1.1 KB
Nov 19, 2017, 9:18 AM


testUtilCreateLRVof3dArray.R
1.4 KB
Nov 18, 2017, 9:05 AM


testUtilCreateOriginalMA1.R
2.3 KB
Nov 6, 2017, 9:15 AM


testUtilCreateOriginalMA1Replicated.R
1.4 KB
Nov 6, 2017, 9:15 AM


testUtilCreateProductCol.R
1.1 KB
Nov 6, 2017, 9:15 AM


testUtilCreateProductColReplicated.r
1.5 KB
Nov 6, 2017, 9:15 AM


testUtilCreateRho.R
693 B
Nov 6, 2017, 9:15 AM


testUtilDrawCvsCHat.R
1.3 KB
Nov 6, 2017, 9:15 AM


testUtilDrawDvsDHat.R
1.3 KB
Nov 19, 2017, 9:18 AM


testUtildrawLrvHatVsTSAVsBasePeriodogram.R
886 B
Nov 22, 2017, 9:29 AM


testUtildrawOriginalLrvHat.R
743 B
Nov 6, 2017, 9:15 AM


testUtilDrawVectorLrvVsLrvHat.R
1.2 KB
Nov 19, 2017, 9:18 AM


testUtilDrawVectorLrvVsLrvHatForSize.R
1.2 KB
Nov 19, 2017, 9:18 AM


testUtilExportOriginal.R
994 B
Nov 6, 2017, 9:15 AM


testUtilLRVProductColReplicated.R
599 B
Nov 6, 2017, 9:15 AM


testUtilObjectSize.R
115 B
Nov 6, 2017, 9:15 AM


testUtilSaveJPG.R
402 B
Nov 19, 2017, 9:18 AM


testUtilSaveProductCol.R
689 B
Nov 6, 2017, 9:15 AM


timestampGenerator.R
157 B
Nov 6, 2017, 9:15 AM
	
experimentWithElapsis.R

	
experimentWithCutter.R

	
cutNB.R

	
createLRVof2dArray.R

	
createProductCol.R

	
ch13.R


			

			
	
			
	
			
	
Source on Save
	
			

			
	
			
	
	


	
Run
	
			
	
	
Source

			
	
			
36:4
	
createProductCol(original)
R Script


27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
  lag = 1
  while ((lengthOriginal - lag) > 0) {
    for (rowIndex in 1:(lengthOriginal - 1)) {
      for (colIndex in 1:(lengthOriginal - lag + 1)) {
        productCol[rowIndex, colIndex] <-
          original[rowIndex] * original[colIndex + lag - 1]
      }
      lag = lag + 1
    }
  }
  #productCol <- as.data.frame(productCol)
  # colnames(productCol) <- as.character(0:(lengthOriginal - 1))
  productCol
}
ConsoleC:/Users/Boris/OneDrive/text/toronto_u/research/zhou/r/product2/product2/

**Comment by av1611** [comment]
cancel commenting out of as.data.frame() of the new created prodCol. ProdCol is going to be fed to the createCHatMatrix() procedure that deals that prodCol as being a data frame, so that as.data.frame() is obligatory.
