### ISSUE TITLE
3 tests fail: CreateQuadraticForm, testUtilOBNBSizeCount, testUtilOBNBSizeCount 

### ISSUE THREAD

**Issue by statistics101** [statistics101/product2#55]
Testing 'tests_93_testUtilBenchmarkComputeLRVofOB2dArray' 
Test parameters: 
size = 10 15 20 25 30 
sigma = 1 
psi = 0.5 
mean = 0 
End of test BenchMark testUtilBenchmarkComputeLRVofOB2dArray 

Warnings -----------------------------------------------------------------------
1. Testing testUtilOBNBSizeCount (@tests_68_testUtilOBFixSampleChangeProp.R#3) - cannot create dir '..\lab\plots', reason 'No such file or directory'

2. Testing testUtilOBNBSizeCount (@tests_68_testUtilOBFixSampleChangeProp.R#3) - unable to open file '../lab/plots/TestDimOB_size_10_28_49.jpg' for writing

3. Testing testUtilOBNBSizeCount (@tests_68_testUtilOBFixSampleChangeProp.R#3) - opening device failed

Failed -------------------------------------------------------------------------
1. Error: Testing CreateQuadraticForm (@tests_17_computeQuadraticFormMatrixFromNB.R#3) 
could not find function "testUtilComputeMatrixFromNB"
1: .handleSimpleError(function (e) 
   {
       e$call <- sys.calls()[(frame + 11):(sys.nframe() - 2)]
       register_expectation(e, frame + 11, sys.nframe() - 2)
       signalCondition(e)
   }, "could not find function \"testUtilComputeMatrixFromNB\"", quote(testUtilComputeMatrixFromNB(size = 10, 
       batchSize = 5))) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/tests/testthat/tests_17_computeQuadraticFormMatrixFromNB.R:3
2: eval(code, test_env)

2. Error: Testing testUtilOBNBSizeCount (@tests_68_testUtilOBFixSampleChangeProp.R#3) 
unable to start jpeg() device
1: testUtilOBFixSampleChangeProp(size = 10, psi = 0.5, sigma = 1, mean = 0, times = 10) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/tests/testthat/tests_68_testUtilOBFixSampleChangeProp.R:3
2: saveJpg(fileName = fileName, path = "../lab/plots") at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/testUtilOBFixSampleChangeProp.R:40
3: jpeg(paste0(path, "/", fileName)) at C:\Users\Boris\OneDrive\text\toronto_u\research\zhou\r\product2\product2/R/saveJpg.R:29

DONE ===========

**Comment by Kosmos42** [comment]
done
